### ISSUE TITLE
main.go/rewrite() broken by latest commit

### ISSUE THREAD

**Issue by klihub** [AdamKorcz/instrumentation#1]
Mandatory disclaimer: I am a total n00b to both this and the github CI Fuzzer action. That said, It seems to me that the recent commit `52025b5d672cd4e2ff3fe84292db819dc4e01cf5` broke `main.go/rewrite()`. For instance I get this errror for containerd both from the CI Fuzz github action and when trying to run the corresponding part of the fuzzer script locally:

```
panic: ../containerd/images/archive/exporter.go:12:2: could not import github.com/containerd/containerd/content (can't find import: "github.com/containerd/containerd/content")

goroutine 1 [running]:
main.rewrite.func1({0xc0000202d0, 0x28}, {0x699830?, 0xc00007e9c0?}, {0x0?, 0x0?})
        /home/kli/src/work/cri/protos/oci/instrumentation/main.go:322 +0x759
path/filepath.walk({0xc0000202d0, 0x28}, {0x699830, 0xc00007e9c0}, 0x659078)
        /scratch0/go/1.19.1/src/path/filepath/path.go:433 +0x123
path/filepath.walk({0xc000022200, 0x1c}, {0x699830, 0xc00007e8f0}, 0x659078)
        /scratch0/go/1.19.1/src/path/filepath/path.go:457 +0x285
path/filepath.walk({0x7ffcf1656de6, 0x14}, {0x699830, 0xc00007e410}, 0x659078)
        /scratch0/go/1.19.1/src/path/filepath/path.go:457 +0x285
path/filepath.Walk({0x7ffcf1656de6, 0x14}, 0x659078)
        /scratch0/go/1.19.1/src/path/filepath/path.go:520 +0x6c
main.rewrite({0x7ffcf1656de6?, 0xc0000061a0?})
        /home/kli/src/work/cri/protos/oci/instrumentation/main.go:293 +0x25
main.main()
        /home/kli/src/work/cri/protos/oci/in
```
Reverting that commit seems to make the problem go away.

**Comment by AdamKorcz** [comment]
Should be fixed in https://github.com/containerd/containerd/pull/7613

**Comment by AdamKorcz** [comment]
Thanks for the report  @klihub
